### ISSUE TITLE
TypeError: Cannot set property errored of #<Readable> which has only a getter

### ISSUE THREAD

**Issue by ghost** [romellem/get-all-links-in-eml-emails#1]
![Screenshot 2023-02-14 133154](https://user-images.githubusercontent.com/125348668/218675101-0bb26d9d-93af-41c5-9e4f-3990987cecd3.png)

C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master>npm start

> emails@1.0.0 start
> node index.js

Found 443 EML files. Enumerating them now...
C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master\node_modules\mailsplit\lib\message-splitter.js:24
        this.errored = false;
                     ^

TypeError: Cannot set property errored of #<Readable> which has only a getter
    at new MessageSplitter (C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master\node_modules\mailsplit\lib\message-splitter.js:24:22)
    at new MailParser (C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master\node_modules\mailparser\lib\mail-parser.js:33:25)
    at module.exports (C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master\node_modules\mailparser\lib\simple-parser.js:25:18)
    at C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master\index.js:20:9
    at Array.forEach (<anonymous>)
    at C:\Users\jay78\Downloads\get-all-links-in-eml-emails-master\index.js:16:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.0

**Comment by Nilsemann** [comment]
Had the same issue. Downgraded NODE to v16 and it worked.
